name: Build
on:
  pull_request:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm
      - name: Install modules
        run: pnpm install
      - name: Run build
        run: pnpm build
      - name: Run git status
        run: git status
      - name: check build is included in branch
        run: test -z "$(git status --porcelain)"
